[toolchain]
# Nightly
channel = "nightly-2024-05-19" # rustc 1.80.0-nightly (d84b90375 2024-05-19)
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
